"""One-shot: cluster the 1000+ unique topic slugs from classify outputs into
~40-50 canonical concepts via Claude Sonnet.

Why Sonnet not Haiku: this is a single-shot semantic-clustering task with high
judgment value. Sonnet handles it cleanly; we run it once.

Output: agent/data/canonical_topics.json with shape:

  {
    "generated_at": "...",
    "model": "...",
    "input_unique_slugs": 1052,
    "canonical_concepts": [
      {
        "id": "memory-management",
        "title": "Memory Management",
        "category": "memory-systems",
        "summary": "How agents persist and recall context across runs",
        "variants": ["memory-systems", "memory-system", "memory-config", ...]
      },
      ...
    ],
    "slug_to_concept": {"memory-systems": "memory-management", ...}
  }

Run:
    agent/.venv/bin/python agent/scripts/canonicalize_topics.py
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "agent"))

CLASSIFY_DIR = REPO_ROOT / "agent" / "data" / "classify"
OUT_PATH = REPO_ROOT / "agent" / "data" / "canonical_topics.json"

MODEL = "sonnet"
EFFORT = "low"  # structured output, no need for deep reasoning
CLI_TIMEOUT_S = 1500  # one-shot; large output (60 concepts × variants)

SYSTEM_PROMPT = """You cluster topic slugs from a developer-community Telegram channel about AI agents, LLMs, coding tools, memory systems, and frameworks.

The user will give you a list of ~1000 topic slugs (kebab-case strings) with their occurrence frequencies. These were generated by a smaller classifier and contain many near-duplicates and trivially-different variants of the same underlying concept (e.g. "memory-systems", "memory-system", "memory-config" all describe agent memory).

Your job: cluster these slugs into 40-60 canonical concepts. Be aggressive about merging variants but conservative about lumping conceptually distinct topics. The goal is a knowledge graph someone can browse — too few concepts means each is overstuffed; too many means the graph is noisy.

Output ONLY a single JSON object with this exact shape — no prose, no markdown fences:

{
  "canonical_concepts": [
    {
      "id": "kebab-case-id",                   // canonical short ID, lowercase kebab-case
      "title": "Human Readable Title",         // for display
      "category": "tools" | "models" | "files" | "systems" | "concepts" | "techniques" | "memory" | "infrastructure" | "workflow" | "people-process" | "other",
      "summary": "One sentence describing what this concept is about.",
      "variants": ["slug1", "slug2", ...]       // all input slugs that map here
    }
  ]
}

Rules:
- Aim for 40-60 concepts total. If you can defensibly stay near 50, do so.
- Every input slug must appear in exactly one `variants` list.
- A "tools" category concept means it's about a SPECIFIC named tool (openclaw, codex, claude-code, obsidian, linear). Generic "tool-comparison" or "coding-tools" goes in "techniques" or "workflow".
- A "files" category concept is about canonical agent-config files (MEMORY.md, SOUL.md, AGENTS.md, etc.). The general practice goes under a related concept.
- A "memory" category concept is about memory architectures and patterns (not specific tools).
- "techniques" = methods/practices (RAG, prompt engineering, semantic search, agent orchestration).
- "workflow" = how-people-actually-work topics (cost optimization, debugging, automation, knowledge management).
- "infrastructure" = MCP, hosting, OAuth, deploys, sync.
- "people-process" = community/channel meta topics (governance, onboarding, marketplace).
- Title case the `title` field.
- Use kebab-case for `id`.
- Single-occurrence slugs that don't fit anywhere → cluster under a broad bucket; do NOT create a one-off concept just because a slug exists once.
"""

USER_TEMPLATE = """Here are {n} unique topic slugs from the corpus, sorted by frequency (most common first). Each line is `count\\tslug`:

{slug_list}

Cluster these into 40-60 canonical concepts per the schema. Output JSON only."""


def _subprocess_env() -> dict[str, str]:
    env = os.environ.copy()
    env.pop("CLAUDECODE", None)
    env.pop("CLAUDE_CODE_ENTRYPOINT", None)
    return env


def _parse_json_lenient(s: str) -> dict:
    s = s.strip()
    if s.startswith("```"):
        s = re.sub(r"^```(?:json)?\s*", "", s)
        s = re.sub(r"\s*```$", "", s)
    try:
        return json.loads(s)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", s, re.DOTALL)
        if not m:
            raise
        return json.loads(m.group(0))


def collect_slugs() -> Counter:
    """Read all classify.json files, return Counter of topic slugs."""
    counter: Counter = Counter()
    for p in sorted(CLASSIFY_DIR.glob("*.json")):
        c = json.loads(p.read_text(encoding="utf-8"))
        for t in c.get("topics", []):
            t = t.strip()
            if t:
                counter[t] += 1
    return counter


def main() -> int:
    slugs = collect_slugs()
    if not slugs:
        print("ERR no classify outputs found", file=sys.stderr)
        return 1

    print(f"== Canonicalizing {len(slugs)} unique slugs ({sum(slugs.values())} total mentions) ==")
    slug_list = "\n".join(f"{c}\t{s}" for s, c in slugs.most_common())

    user_prompt = USER_TEMPLATE.format(n=len(slugs), slug_list=slug_list)

    cmd = [
        "claude", "-p",
        "--model", MODEL,
        "--effort", EFFORT,
        "--output-format", "json",
        "--no-session-persistence",
        "--tools", "",
        "--disable-slash-commands",
        "--system-prompt", SYSTEM_PROMPT,
    ]
    print(f"Calling claude --model {MODEL} --effort {EFFORT} (may take 1-3 min)...")
    proc = subprocess.run(
        cmd, input=user_prompt, capture_output=True, text=True,
        timeout=CLI_TIMEOUT_S, env=_subprocess_env(),
    )
    if proc.returncode != 0:
        print(f"ERR claude exit {proc.returncode}: {proc.stderr[:500]}", file=sys.stderr)
        return 1

    envelope = json.loads(proc.stdout)
    if envelope.get("is_error"):
        print(f"ERR claude reported error: {envelope.get('result')}", file=sys.stderr)
        return 1

    raw = _parse_json_lenient(envelope["result"])
    concepts = raw.get("canonical_concepts", [])
    if not concepts:
        print(f"ERR no canonical_concepts in output: {raw}", file=sys.stderr)
        return 1

    # Build the slug → concept_id reverse map and validate coverage
    slug_to_concept: dict[str, str] = {}
    for c in concepts:
        for v in c.get("variants", []):
            slug_to_concept[v] = c["id"]

    covered = sum(1 for s in slugs if s in slug_to_concept)
    uncovered = [s for s in slugs if s not in slug_to_concept]
    if uncovered:
        print(f"WARN {len(uncovered)} slugs not mapped, first 10: {uncovered[:10]}")

    out = {
        "$schema": "canonical_topics.v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "model": MODEL,
        "input_unique_slugs": len(slugs),
        "input_total_mentions": sum(slugs.values()),
        "canonical_concept_count": len(concepts),
        "coverage_pct": round(100 * covered / len(slugs), 1),
        "uncovered_slugs": uncovered,
        "canonical_concepts": concepts,
        "slug_to_concept": slug_to_concept,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"\nOK wrote {OUT_PATH}")
    print(f"   {len(concepts)} canonical concepts")
    print(f"   {covered}/{len(slugs)} slugs mapped ({out['coverage_pct']}%)")
    print(f"\nBy category:")
    cat_counts = Counter(c.get("category", "?") for c in concepts)
    for cat, n in cat_counts.most_common():
        print(f"   {n:>3}  {cat}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
